(function($) {
	window.fnames = new Array();
	window.ftypes = new Array();
	fnames[5] = 'MMERGE5';
	ftypes[5] = 'radio';
	fnames[1] = 'FNAME';
	ftypes[1] = 'text';
	fnames[2] = 'LNAME';
	ftypes[2] = 'text';
	fnames[0] = 'EMAIL';
	ftypes[0] = 'email';
	fnames[6] = 'MMERGE6';
	ftypes[6] = 'text';
	fnames[4] = 'PHONE';
	ftypes[4] = 'phone';
	fnames[3] = 'MMERGE3';
	ftypes[3] = 'dropdown';
	fnames[7] = 'MMERGE7';
	ftypes[7] = 'dropdown';
})(jQuery);
const $mcj = jQuery.noConflict(true);
